[33기 박상연] Mission 3: 회원가입 기능 구현
wecode-bootcamp-korea/33-backend-westagram-2 pull request #10
Opened 2022-05-13 11:37 UTC by ysang989

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 회원가입 엔드포인트 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-05-14 05:00 UTC, lordmyshepherd requested changes

2022-05-14 05:00 UTC, lordmyshepherd commented on students/sangyeon/users/views.py
> +        password_check = '^.*(?=.{8,})(?=.*\d)(?=.*[a-z])(?=.*[@#$%^&+=]).*$'
정규 표현식은 변하지 않는 상수이기 때문에, python 컨벤션에 맞게 대문자로 만들어주셔야 합니다!
```suggestion
        REGEX_EMAIL = '[a-zA-Z0-9_-]+@[a-z]+.[a-z]+$'
        REGEX_PASSWORD = '^.*(?=.{8,})(?=.*\d)(?=.*[a-z])(?=.*[@#$%^&+=]).*$'
```

2022-05-14 05:00 UTC, lordmyshepherd commented on students/sangyeon/users/views.py
> +            return JsonResponse({"message": "KEY_ERROR"}, status=400)
KeyError는 어떤 경우에 발생하나요?
try, except 블록이 잘 설정되었는지 다시한번 확인해보시면 좋을 것 같습니다-!

2022-05-15 03:34 UTC, ysang989 commented on students/sangyeon/users/views.py
> +        password_check = '^.*(?=.{8,})(?=.*\d)(?=.*[a-z])(?=.*[@#$%^&+=]).*$'
수정하였습니다!

2022-05-15 04:05 UTC, ysang989 commented on students/sangyeon/users/views.py
> +            return JsonResponse({"message": "KEY_ERROR"}, status=400)
제기 찾아본 바로는 KeyError는 딕셔너리에 존재하는 키를 입력할때나 입력하지 않았을 때 발생한다고 알고 있습니다. 피드백에 따라 try, except를 다시 확인 했지만 어떤 부분에서 잘못된 것인지 모르겠습니다. 그래서 찾아보니 저와 같이 바로 except로 쓰신 분과 try에 if로 경우를 또 쓰신 분이 계셔서 저도 일단 if를 추가 했습니다만 맞는지 잘 모르겠습니다.

2022-05-16 01:40 UTC, autoboy4commit commented on students/sangyeon/users/views.py
> +
상연님~ 말씀해주신 것 처럼 KeyError는 다음과 같이 요청으로 함께 들어와야 하는 키 값이 누락되었을 때 나타납니다!

다음은 cilent의 요청 시 KeyError가 아닌 경우와 KeyError인 경우의 예시입니다.
```bash
http -v POST 127.0.0.1:8000/users/signup name="..." email="" password="" phone_number="..."   (KeyError X)
http -v POST 127.0.0.1:8000/users/signup name="..." phone_number="..."   (KeyError O)
```
line 57의 except로 KeyError를 캐치하기 위해서는 try의 범위가 line 29~32를 포함하고 있어야겠죠?

추가로 line 34, 35는 필요없는 코드로 보입니다! 위에서 설명한 것과 같이 `email='' password=''` 같은 경우는 키가 누락되는 KeyError가 아닌 빈값이 들어오는 경우이며 공백이 들어오는 예외 상황은 밑줄의 정규표현식을 통한 유효성 검사 로직에서 걸러지기 때문입니다.

 ```suggestion
    def post(self, request):
        try:
            input_data = json.loads(request.body)

            name         = input_data["name"]
            email        = input_data["email"]
            password     = input_data["password"]
            phone_number = input_data["phone_number"]

            EGEX_EMAILR = '[a-zA-Z0-9_-]+@[a-z]+.[a-z]+$'
            REGEX_PASSWORD = '^.*(?=.{8,})(?=.*\d)(?=.*[a-z])(?=.*[@#$%^&+=]).*$'
 
```

2022-05-16 04:28 UTC, ysang989 commented on students/sangyeon/users/views.py
> +
수정완료했습니다!

2022-05-16 04:32 UTC, autoboy4commit commented
LGTM 👍

2022-05-16 04:32 UTC, merged