[임한구] Mission 3: 회원가입 기능 구현
wecode-bootcamp-korea/33-backend-westagram-2 pull request #9
Opened 2022-05-13 08:43 UTC by nicholas019

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 회원가입구현
- re 사용
- compile, match 사용
- 정규표현식 활용하여 유효성검사 진행
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-05-13 09:26 UTC, lordmyshepherd requested changes

2022-05-13 09:26 UTC, lordmyshepherd commented on students/hangu/users/views.py
> +            phone_number_validation = re.compile("^01([0|1|6|7|8|9])-?([0-9]{3,4})-?([0-9]{4})$")
정규표현식을 사용할 경우, 자주 사용되는 경우가 아니라면 `compile()`해서 사용하지 않고, `match()`를 사용하는 것을 공식 문서에서 추천하고 있습니다.

```python
import re

REGEX_EMAIL    = '^[a-zA-Z0-9+-_.]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$'
REGEX_PASSWORD = '^(?=.*[A-Za-z])(?=.*\d)(?=.*[$@$!%*#?&])[A-Za-z\d$@$!%*#?&]{8,}$'
    
    if not re.match(REGEX_EMAIL, value):

    if not re.match(REGEX_PASSWORD, value):

```

2022-05-13 09:26 UTC, lordmyshepherd commented on students/hangu/users/views.py
> +            if user_email is None:
사용자의 존재 유무만 판단하는 경우에 first() 메소드로 객체를 가져오는 것 보다는 .exists() 함수로 True 혹은 False만 가져오는 것이 성능상 이득을 볼 수 있습니다. 찾아보고 적용 부탁드립니다-!

```suggestion
            user_email = User.objects.filter(user_email = user_email).first()
            if user_email is None:
```

2022-05-16 01:21 UTC, lordmyshepherd requested changes

2022-05-16 01:21 UTC, lordmyshepherd commented on students/hangu/users/views.py
> +                return JsonResponse({"message":"이메일 또는 비밀번호를 입력해주세요"}, status=400)
line 22~23 코드는 필요 없을 것 같습니다.

만약에 client에서 요청을 보낼 때,
```bash
Case 1. http -v GET 127.0.0.01:8000/signup phone_number="010..."
Case 2. http -v GET 127.0.0.01:8000/signup email = "" password = "" phone_number="010..."
```

Case 1 이라면 try, except에서 KeyError 처리가 가능합니다.
Case 2 라면 line 25, 28에서 정규표현식에서 "" 값이 필터링이 될 것입니다.

그러므로 22~23 코드는 필요 없을 것 같습니다.

2022-05-16 02:39 UTC, lordmyshepherd commented on students/hangu/users/views.py
> +                return JsonResponse({"message":"이메일 또는 비밀번호를 입력해주세요"}, status=400)
코멘트에 답변 혹은 이모지를 붙여주셔야 피드백이 제대로 전달되었는지 알 수 있습니다.

2022-05-16 02:40 UTC, nicholas019 commented on students/hangu/users/views.py
> +                return JsonResponse({"message":"이메일 또는 비밀번호를 입력해주세요"}, status=400)
pr을 수정했는데 코맨트도 달겠습니다 죄송합니다

2022-05-16 02:45 UTC, autoboy4commit commented
LGTM 👍

2022-05-16 02:46 UTC, merged